#!/bin/bash
set -e 

# function to print usage info
usage () {
    echo "Usage:"
    echo "    $0 [OPTIONS] [URL ...]"
    echo
    echo "Options:"
    echo "    -c|--config FILE      read defaults and options from FILE,"
    echo "                          defaults to \$HOME/.httptailrc"
    echo "    -p|--preset STRING    selects named preset from configuration file"
    echo "    -n|--count NUM        output last NUM bytes, defaults to 4096"
    echo "    -f|--follow           append data to the output as the file grows"
    echo "    -i|--interval NUM     check for updates every NUM seconds, defaults to 1,"
    echo "                          only makes sense with --follow"
    echo "    -s|--start NUM        output starts at byte NUM, defaults to 0,"
    echo "                          this option is mutually exclusive with --count"
    echo "    -e|--end NUM          output ends at byte NUM, defaults to end of file,"
    echo "                          this option is mutually exclusive with --count"
    echo "    -P|--prepend          prefix each line with file url"
    echo "    -x|--debug            debug mode"
    echo "    -h|--help             print help (this text)"
    echo
    echo "Examples:"
    echo "    Print last 10kb:"
    echo "        $0 -c 10240 'http://example.com/path/file.log'"
    echo "    Print everything from byte 1024 to 2048:"
    echo "        $0 -s 1024 -e 2048 'http://example.com/path/file.log'"
    echo "    Print what was appended to the file on the server every 0.5s:"
    echo "        $0 -f -i 0.5 'http://example.com/path/file.log'"
    exit "$1"
}

prepend () {
    "$@" | sed "s|^|${urls[$i]}: |";
}

password_prompt () {
    # shellcheck disable=SC2016
    echo "Password${USER:+ for '$USER'}:"
    read -r -s PASSWORD;
}

preset () {
    case $NAME in
        "")         PREFIX="GLOBAL" ;;
        "$preset")  PREFIX="PRESET" ;;
        *)          PREFIX="" ;;
    esac
    if [ "$PREFIX" ] ; then
        for x in PROXY FILE COUNT INTERVAL USER PASSWORD; do
            if [ "${!x+set}" ]; then
                eval "${PREFIX}_$x=\"${!x}\""
            fi
        done
        for x in SERVERS OPTS; do
            local VAR="$x""[0]"
            if [ "${!VAR+set}" ]; then
                VAR="$x""[@]"
                eval "${PREFIX}_$x"='("'"${!VAR}"'")'
            fi
        done
    fi
    NAME="$1"
    for x in PROXY FILE COUNT INTERVAL USER PASSWORD SERVERS OPTS; do
        unset "$x"
    done
}

coalesce () {
    local OUT="$1";
    shift
    for ((i=1; i<=$#; i++)); do
        local VAR="${!i}"
        [ "${!VAR+set}" ] || continue
        eval "$OUT=\"${!VAR}\""
        return
    done
}

coalesce_array () {
    local OUT="$1"
    shift
    for ((i=1; i<=$#; i++)); do
        local VAR="${!i}[*]"
        [ "${!VAR+set}" ] || continue
        VAR="${!i}[@]"
        eval "$OUT=(\"""${!VAR}""\")"
        return
    done
}

merge_config () {
    coalesce PROXY             PRESET_PROXY    GLOBAL_PROXY
    coalesce FILE              PRESET_FILE     GLOBAL_FILE
    coalesce COUNT    count    PRESET_COUNT    GLOBAL_COUNT    DEFAULT_COUNT
    coalesce INTERVAL interval PRESET_INTERVAL GLOBAL_INTERVAL DEFAULT_INTERVAL
    coalesce USER              PRESET_USER     GLOBAL_USER
    coalesce PASSWORD          PRESET_PASSWORD GLOBAL_PASSWORD

    coalesce_array SERVERS PRESET_SERVERS GLOBAL_SERVERS
    coalesce_array OPTS    PRESET_OPTS    GLOBAL_OPTS
}

parse_args () {
    # parse command line
    urls=()
    while [ $# -gt 0 ]; do
    case "$1" in
    -f|--follow)   follow="1";     shift 1 ;;
    -i|--interval) interval="$2";  shift 2 ;;
    -s|--start)    start="$2";     shift 2 ;;
    -e|--end)      end="$2";       shift 2 ;;
    -n|--count)    count="$2";     shift 2 ;;
    -c|--config)   config="$2";    shift 2 ;;
    -p|--preset)   preset="${2}";  shift 2 ;;
    -P|--prepend)  prep="prepend"; shift 1 ;;
    -x|--debug)    set -x; dbg=-v; shift 1 ;;
    -h|--help)     usage 0 ;;
    *)             urls+=( "$1" ); shift 1 ;;
    esac
    done
}

configure () {
    DEFAULT_COUNT=4096
    DEFAULT_INTERVAL=1

    if [ -e "$HOME/.httptailrc" ]; then
        config="$HOME/.httptailrc"
    else
        config="/etc/httptailrc"
    fi

    parse_args "$@"

    #TODO: allow start && follow and combinations with count
    if [[ "$count" && "$start" ]] || [[ "$count" && "$end" ]] || [[ "$start" && "$follow" ]] || [[ "$end" && "$follow" ]]; then
        echo "Wrong combination of parameters!" >> /dev/stderr
        usage 3;
    fi

    # read configuration file
    # shellcheck source=httptailrc
    . "$config"
    preset

    merge_config

    # process login information
    if [ "$PASSWORD" = "ASK" ]; then
        password_prompt
    fi
    if [ "$USER" ] || [ "$PASSWORD" ]; then
        # to hide the password from debug log, we create unnamed file
        # and pass its file descriptor to curl as config
        # TODO: try this without even the fd (using curl -K - <<<"user = $USER:$PASSWORD")
        local TMPDATA
        TMPDATA="$(mktemp)"
        exec 9<> "$TMPDATA"
        rm "$TMPDATA"
        cat <<<"user = $USER:$PASSWORD" > /dev/fd/9
        OPTS+=('--config' '/dev/fd/9')
    fi

    # construct array with all the urls
    #TODO: make this work when only one of FILE and SERVERS is defined
    if [[ -n "$FILE" && -n "${SERVERS[0]}" ]]; then
        urls=()
        for s in "${SERVERS[@]}"; do urls+=( "$s/$FILE" ); done
    fi

    # set proxy
    if [ "$PROXY" ];then
        export http_proxy="$PROXY"
        export https_proxy="$PROXY"
    fi

    # set interval
    interval="${INTERVAL:-$interval}"
}

get_length() {
    curl "${dbg:---silent}" "${OPTS[@]}" --head "$1" | sed -n 's/\r//;s/Content-Length: //p;'
}

calculate_range () {
    if [ "$start" ]; then
        if [ "$end" ]; then
            len="$(get_length "$1")"
            range="$start-$(( len - end - 1 ))"
        else
            range="$start-"
        fi
    else
        if [ "$end" ]; then
            range="-$end"
        else
            range="-${count:-${COUNT:-4096}}"
        fi
    fi
    # check that the range has correct values
    echo "$range" | grep -q "[0-9]*-[0-9]*" || usage 4
}

main () {
    configure "$@"

    url_count=${#urls[@]}

    # get the data
    if [ "$follow" ]; then
        for (( i=0; i<url_count; i++ )); do
            lastlen[$i]="$(( "$(get_length "${urls[$i]}")" - ${count:-${COUNT:-4096}} ))"
            lastlen[$i]="$(( "${lastlen[$i]}" > 0 ? "${lastlen[$i]}" : 0 ))"
        done;
        while true; do
            for (( i=0; i<url_count; i++ )); do
                len="$(get_length "${urls[$i]}")"
                [ "${lastlen[$i]}" != "$len" ] && $prep curl "${dbg:---silent}" "${OPTS[@]}" --range "${lastlen[$i]}-" "${urls[$i]}"
                lastlen[$i]="$len"
            done
            sleep $interval
        done
    else
        for (( i=0; i<url_count; i++ )); do
            calculate_range "${urls[$i]}"
            $prep curl "${dbg:---silent}" "${OPTS[@]}" --range "$range" "${urls[$i]}"
        done
    fi

    # add a newline, to make it look better in terminal in case when downloaded
    # data do not end with newline
    echo
}

main "$@"
